spring:
  datasource:
    url: jdbc:mysql://localhost:3306/produtoECategoriaAC1?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
springdoc:
  api-docs:
    path: /api-docs