spring:
  datasource:
    url: jdbc:mysql://localhost:3306/produto?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    path: /api-docs